### ISSUE TITLE
Modified BUILDING.md

### ISSUE THREAD

**Issue by 3d-gussner** [thess/Prusa-Firmware#1]
Hi Thess,

check my modified BUILDING.md
https://github.com/3d-gussner/Prusa-Firmware/blob/MK2-Private_build/BUILDING.md

**Comment by thess** [comment]
OK, you asked...

I like the additional information about working with language options. I think that 'Step 5' however, should be in a separate, perhaps stand-alone,  document. It really doesn't go with the flow of just building firmware.

You shouldn't need to mention things Prusa should or didn't do as that solves nothing - eliminate sentence: "It is a pity Prusa didn't go for the HD44780 A02 ROM version with western european ROM.". Also, it is possible to build a single-language version ot the firmware with my version of langtool.pl (It also knows how to skip commented out lines).

'Step 8' - This info probably should be in the README since it is un-related to building.

Is __le.sh__ really needed? One should be able to use __dos2unix__ on almost all platforms (use package installer if necessary). Better yet, you can set **git** to do the translations (that is, make it right) transparently. Ref: https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings#10419350

One last comment... I use numbered elements in a list when an "order" is needed. Otherwise bullets are "un-ordered". Instructional steps are usually ordered.
